default_project: 'MAST'
default_queue: 'local'

projects:
  MAST:
    dir: '/cluster/personal/MAST' # Replace $WORK/projects by location of MAST directory
    preamble: 'job-runner-preamble.sh'
    conda_env: '/opt/conda'
    default_queue: 'local'

conda:
  root: '/opt/conda' # Path to anaconda installation

storage:
  root: '/cluster/personal/MAST/local_data/jobs' # Where to store information of the jobs

gpu_queues:
  gpu_p1:  # Provide SLURM information relative to the queue you want to use
    n_cpus_per_node: 40
    n_gpus_per_node: 4
    flags:
      partition: 'gpu_p1'
      time: '20:00:00'
      hint: 'nomultithread'
      qos: 'qos_gpu-t3'

  local:  # Don't touch this
    n_cpus_per_node: 'auto'
    n_gpus_per_node: 'auto'
